### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 687766616e** [gfek/Lepus#10]
shodan always `Please upgrade your API plan to use filters or paging.` even I register a new account...

**Comment by 687766616e** [comment]
ip limit? or lepus bug?

**Comment by GKNSB** [comment]
This has to do with how shodan manages the filtered searches. I believe you have to use a paid shodan account for this to work properly, however I'll look into it more.

**Comment by GKNSB** [comment]
Give the latest version a go and let us know.

**Comment by gfek** [comment]
marked it as a close issue.
