### ISSUE TITLE
Spyse API Key (Update)

### ISSUE THREAD

**Issue by Greg-spec** [gfek/Lepus#11]
We noticed that you used the API of one of Spyse's products most likely it was Findsubdomains, Cert DB or DNS table. We want to notify you about the release of a new and improved API key which you can find in your personal account at spyse.com. 
Unfortunately, we should stop supporting the old API a few weeks earlier, starting from Monday. Thanks for being with us.

**Comment by gfek** [comment]
Thank you for your message. We are aware about that and we will proceed with the update.

**Comment by gfek** [comment]
marked it as a close issue.
