### ISSUE TITLE
Missing PIP dependency

### ISSUE THREAD

**Issue by naliferopoulos** [gfek/Lepus#13]
It appears that the following repo which is marked as a dependency on requirements.txt has been taken down:
- https://github.com/VeNoMouS/cloudflare-scrape-js2py

I am not sure whether this requirement can be bypassed in the current version of Lepus.

Thank you for the awesome work :)

**Comment by gfek** [comment]
Hi Nick,

Thank you. We will do an update, although it will take some time due to a lack of time. In the mean time you can experiment :)

**Comment by GKNSB** [comment]
Dependencies should be fixed in the latest version.

**Comment by gfek** [comment]
mark it as a close issue.
