### ISSUE TITLE
 Spyse API Key (Update)

### ISSUE THREAD

**Issue by Greg-spec** [gfek/Lepus#14]
Hi there. You previously used one of our services as a part of your development. We want to notify you, that we are releasing our updated Spyse API search. We hope you will be interested in testing and implementing a much broader functionality to your developments. Thanks for being with us.

**Comment by GKNSB** [comment]
Thanks Greg. Indeed the new API is a lot broader. We are looking into it.

**Comment by Greg-spec** [comment]
Hi there, 

Please, let me know if you will have any questions. 


BR,
Gregory Spec
Communication ninja
Linkedin <http://linkedin.com/in/gregory-speccccc/>
spyse.com
 <http://spyse.com/>

**Comment by gfek** [comment]
mark it as a close issue.
