### ISSUE TITLE
pls support fofa.so zoomeye.org

### ISSUE THREAD

**Issue by c2xusnpq6** [gfek/Lepus#16]
fofa.so zoomeye.org just like the others~ (ex. censys shodan)

but lot… lot more result ~~

**Comment by c2xusnpq6** [comment]
https://www.zoomeye.org/discover
https://github.com/knownsec/ZoomEye-python

**Comment by GKNSB** [comment]
We are building a new version that will be up soon. We'll look into those collectors but we have to test them first. Thanks for bringing it up.

**Comment by c2xusnpq6** [comment]
and this one too~ https://quake.360.cn/quake/#/index

**Comment by c2xusnpq6** [comment]
https://github.com/fofapro

https://github.com/fofapro/fofa-py
https://github.com/fofapro/fofa-java
https://github.com/fofapro/fofa-go
https://github.com/fofapro/fofa-c

@GKNSB @gfek

**Comment by c2xusnpq6** [comment]
and I found something very interesting.....

Hosts_scan: https://github.com/fofapro/Hosts_scan

bad eng... so.....
google translate: 
This is a small tool for IP and domain name collision matching access. It is designed to match weak hosts or internal systems that need to be bound to access during the infiltration process.
microsoft translate:
This is a gadget for IP and domain name collision matching access, intended to match weak hosts or internal systems that need to be bound to access during penetration.

**Comment by c2xusnpq6** [comment]
https://subdomainfinder.c99.nl/

**Comment by c2xusnpq6** [comment]
https://www.icpapi.com/

https://www.icpapi.com/api.html

**Comment by c2xusnpq6** [comment]
https://github.com/Cl0udG0d/Fofa-script (https://www.cnblogs.com/Cl0ud/p/14324445.html)

https://github.com/fofapro

https://github.com/sv3nbeast/X-Fofa
https://github.com/piaolin/fofa2Xray

**Comment by gfek** [comment]
Not it's supported. Many thanks.
