### ISSUE TITLE
DNSDB is now dead, pls remove

### ISSUE THREAD

**Issue by c2xusnpq6** [gfek/Lepus#17]
![image](https://user-images.githubusercontent.com/75058881/112700563-6a6c8680-8ec9-11eb-9c7d-ca47f65a257d.png)
![image](https://user-images.githubusercontent.com/75058881/112700574-71939480-8ec9-11eb-9ddb-411e3e953982.png)

**Comment by c2xusnpq6** [comment]
@gfek

**Comment by GKNSB** [comment]
@c2xusnpq6 we are working on a new version with new features and many fixes, including the one you mentioned. Thanks for bringing it up.
