### ISSUE TITLE
List of hosts output / query db

### ISSUE THREAD

**Issue by retpoline** [gfek/Lepus#20]
Hi there,

I don't see any -o / output to text file options, nor is it immediately obvious how to use Lepus to pull these out of the database via command line to generate eg. a list of found hosts.

Any ideas?

Thanks!

**Comment by gfek** [comment]
Hey!!! thank you for your message.

Lepus creates different csv files, e.g. asn/networks/records/resolved etc.,  under the folder findings.

**Comment by retpoline** [comment]
Ah, I see. That makes sense!

Perhaps you could talk a little more about output and options in that regard in the README as I didn't find output options, csv files or other output details there AFAIK.

Thanks for your time and awesome project!

**Comment by gfek** [comment]
We will plan to update the README file. Thanks again.
