### ISSUE TITLE
Error when it's performing RDAP lookups

### ISSUE THREAD

**Issue by hxlxmjxbbxs** [gfek/Lepus#25]
traceback (most recent call last):
  File "/home/kali/Lepus/lepus.py", line 154, in <module>
    utilities.ScanHelpers.massRDAP(db, args.domain, args.threads)
  File "/home/kali/Lepus/utilities/ScanHelpers.py", line 690, in massRDAP
    if record["asn"] != "NA" and record["asn_cidr"] != "NA" and record["asn_description"] != "NA":
KeyError: 'asn_description'

**Comment by GKNSB** [comment]
What was your exact command that resulted in that error? I have not been able to replicate this.

**Comment by gfek** [comment]
no response, can't repro.
