### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by huitc** [gfek/Lepus#3]
```
python3 lepus.py --takeover --portscan --reverse --permutate -zt -t 10 test.com.us

...
[*]-Loading Old Findings...                                         \__ Unique subdomains loaded: 0
Traceback (most recent call last):                                  File "lepus.py", line 71, in <module>                               old_findings, old_resolved_public, last_run, collector_hosts = utilities.MiscHelpers.loadOldFindings(args.domain)                 File "/data/data/com.termux/files/home/sub5/utilities/MiscHelpers.py", line 180, in loadOldFindings                                   return OF, ORP, last_run, collector_results                   UnboundLocalError: local variable 'last_run' referenced before assignment
$ 
```

**Comment by GKNSB** [comment]
Hey there huitc,

The only way we've been able to replicate the error is by manually removing the .timestamp file from the respective domain folder in ./results/.  The file is normally needed during run of the program. In case you actually delete all the contents of the domain folder, the error does not occur and all content is regenerated.

Is there some specific reason you actually deleted the timestamp file for? Could you share your replication steps if that wasn't actually the way you encountered the error?

**Comment by huitc** [comment]
```
python3 lepus.py --takeover --portscan --reverse --permutate -zt -t 10 canttellyou.com

[*]-Searching Entrust Certificates...
  \__ Expecting value: line 1 column 1 (char 0)
```

**Comment by huitc** [comment]
> Hey there huitc,
> 
> The only way we've been able to replicate the error is by manually removing the .timestamp file from the respective domain folder in ./results/. The file is normally needed during run of the program. In case you actually delete all the contents of the domain folder, the error does not occur and all content is regenerated.
> 
> Is there some specific reason you actually deleted the timestamp file for? Could you share your replication steps if that wasn't actually the way you encountered the error?

Maybe it was because I suddenly pressed `ctrl + c` or reboot my pc... something like that....😅

**Comment by huitc** [comment]
Or is it due to a connection problem?  I'm not so sure either

**Comment by GKNSB** [comment]
It mustn't have been due to connectivity problems. It was probably because the execution was forcefully interrupted for some reason. Issue can be closed.

**Comment by huitc** [comment]
how about this one?😅
```
$ python3 lepus.py --takeover --portscan --reverse --permutate -zt -t 100 test.com.us
         ______  _____           ______
 |      |______ |_____) |     | (_____
 |_____ |______ |       |_____| ______)
                                v3.1.0
[*]-Retrieving DNS Records...
(hidden)

[*]-Loading Old Findings...
  \__ Unique subdomains loaded: 0
Traceback (most recent call last):
  File "lepus.py", line 71, in <module>
    old_findings, old_resolved_public, last_run, collector_hosts = utilities.MiscHelpers.loadOldFindings(args.domain)
  File "/data/data/com.termux/files/home/sub5/utilities/MiscHelpers.py", line 180, in loadOldFindings
    return OF, ORP, last_run, collector_results
UnboundLocalError: local variable 'last_run' referenced before assignment
$
```
