### ISSUE TITLE
about dns server rate limiting

### ISSUE THREAD

**Issue by huitc** [gfek/Lepus#5]
https://community.cloudflare.com/t/1-1-1-1-rate-limiting/39290/6
Can I set a limit of 10 or 30 whatever~ queries per second?

and.. sometimes the device will continue to query even if it is not connected to the Internet. (google translated

**Comment by GKNSB** [comment]
We have not experienced any form of rate limiting from dns servers whatsoever. Plus, a rate of 10/30 queries per second would be terribly slow. The second line makes pretty much no sense.
