### ISSUE TITLE
add search engine

### ISSUE THREAD

**Issue by 687766616e** [gfek/Lepus#8]
search: `domain="{domainname}"`
like this: https://fofa.so/result?q=domain%3D%22github.com%22&qbase64=ZG9tYWluPSJnaXRodWIuY29tIg%3D%3D&full=true

if `full=true` then show all record else only show records for one year (google translated

_Originally posted by @huitc in https://github.com/gfek/Lepus/issues/4#issuecomment-516601573_

**Comment by huitc** [comment]
https://github.com/gfek/Lepus/issues/4#issuecomment-516602873

**Comment by 687766616e** [comment]
or search website title to get more information (if using cdn
example:

**Comment by GKNSB** [comment]
FOFA has been added in the latest version.

**Comment by gfek** [comment]
marked it as a close issue.
